// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1faBKOXwNOm6MK2I9d2vx6xuhC3qLjOs',
    appId: '1:561598111168:web:15367f3b49738499a7bc25',
    messagingSenderId: '561598111168',
    projectId: 'hackathon-50b37',
    authDomain: 'hackathon-50b37.firebaseapp.com',
    storageBucket: 'hackathon-50b37.appspot.com',
    measurementId: 'G-6ZZCBL3K4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnR7DWZhYhcVMvzKqklhwZbCDw0mM9pOM',
    appId: '1:561598111168:android:fc57b0635e43df30a7bc25',
    messagingSenderId: '561598111168',
    projectId: 'hackathon-50b37',
    storageBucket: 'hackathon-50b37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHf80a0_YYwDnLSKOAVmtSH70RFkSTKww',
    appId: '1:561598111168:ios:88ea76bd718e3da1a7bc25',
    messagingSenderId: '561598111168',
    projectId: 'hackathon-50b37',
    storageBucket: 'hackathon-50b37.appspot.com',
    iosClientId: '561598111168-0m7g2kjr678vpelrjmi9ehq16jrj8hnf.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackathon',
  );
}
